In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

In [26]:
#Importing one of the results:
filepath = '/lustre/storeB/project/fou/hi/foccus/experiments/benchmark/logs/mlflow/373674504653063552/ad83347a4e664d9397d6600f4102ab84/metrics'
""" 
For an overfitting analysis - we focus on the validation and training loss, with epochs on the x-axis. We will be importing the relevant metrics only for simplicity
I believe the metrics are given as: ['ID', 'Vals', 'Steps']
"""
epochs_0 = pd.read_csv(f'{filepath}/epoch', header = 0)
val_loss_epoch_0 = pd.read_csv(f'{filepath}/val_multi_dataset_loss_epoch', header = 0)
train_loss_epoch_0 = pd.read_csv(f'{filepath}/train_multi_dataset_loss_epoch', header = 0)

epochs = epochs_0.columns = ['ID', 'Vals', 'Steps']

ValueError: Length mismatch: Expected axis has 1 elements, new values have 3 elements

In [23]:
epochs

           1786455573861 0.0 99
0         1786455959962 0.0 199
1         1786456346245 0.0 299
2         1786456732705 0.0 399
3         1786457119075 0.0 499
4         1786457505474 0.0 599
...                         ...
1504  1787058242394 40.0 146599
1505  1787058629810 40.0 146699
1506  1787059017371 40.0 146799
1507  1787059405408 40.0 146899
1508  1787059796267 40.0 146999

[1509 rows x 1 columns]

In [24]:
val_loss_epoch

       1786470017272 0.03139052540063858 3606
0      1786484854533 0.02168354019522667 7213
1    1786499687323 0.016852010041475296 10820
2    1786514528620 0.015668267384171486 14427
3    1786529375333 0.014507336542010307 18034
4    1786544218348 0.013844898901879787 21641
5    1786559069668 0.012718341313302517 25248
6    1786573919815 0.012375323101878166 28855
7    1786588774533 0.012283685617148876 32462
8    1786603626815 0.011729933321475983 36069
9    1786618480712 0.011709918268024921 39676
10    1786633338076 0.01124600414186716 43283
11   1786648190734 0.011415769346058369 46890
12   1786663044669 0.010727903805673122 50497
13   1786677896727 0.010780902579426765 54104
14   1786692742475 0.010294053703546524 57711
15    1786707593371 0.01043921709060669 61318
16   1786722440154 0.010433291085064411 64925
17   1786737290945 0.010318385437130928 68532
18   1786752143269 0.010148430243134499 72139
19    1786766990208 0.01044490560889244 75746
20   1786781841150 0.010164556093513966 79353
21   1786796691574 0.010240317322313786 82960
22   1786811545349 0.009528769180178642 86567
23   1786826396074 0.009776497259736061 90174
24    1786841244500 0.00980082992464304 93781
25   1786856099152 0.009684623219072819 97388
26  1786870952060 0.009957166388630867 100995
27  1786885812832 0.009424467571079731 104602
28  1786900669286 0.009117732755839825 108209
29  1786915521303 0.009412170387804508 111816
30  1786930376178 0.009285790845751762 115423
31   1786945233147 0.00927467830479145 119030
32   1786960093347 0.00891223456710577 122637
33  1786974949871 0.008833370171487331 126244
34   1786989807882 0.00852777436375618 129851
35  1787004669762 0.008732818998396397 133458
36  1787019525019 0.008751333691179752 137065
37  1787034377445 0.008657327853143215 140672
38  1787049241032 0.008652091957628727 144279

In [25]:
train_loss_epoch

       1786470024391 0.06313081085681915 3606
0     1786484858439 0.023810671642422676 7213
1    1786499691010 0.018538570031523705 10820
2     1786514532303 0.01602097973227501 14427
3    1786529379021 0.014474357478320599 18034
4     1786544221925 0.01354836393147707 21641
5    1786559073329 0.012842057272791862 25248
6    1786573923455 0.012350562028586864 28855
7    1786588778196 0.011953864246606827 32462
8    1786603630449 0.011571760289371014 36069
9    1786618484386 0.011274779215455055 39676
10   1786633341764 0.011050195433199406 43283
11   1786648194417 0.010808584280312061 46890
12   1786663048336 0.010623465292155743 50497
13   1786677900366 0.010450456291437149 54104
14   1786692746148 0.010295482352375984 57711
15   1786707597066 0.010142841376364231 61318
16    1786722443827 0.01002837810665369 64925
17     1786737294627 0.0098696518689394 68532
18   1786752146887 0.009745565243065357 72139
19    1786766993787 0.00965659786015749 75746
20    1786781844819 0.00956355407834053 79353
21   1786796695275 0.009472406469285488 82960
22    1786811549005 0.00936853140592575 86567
23   1786826399709 0.009279927238821983 90174
24    1786841248169 0.00921704899519682 93781
25   1786856102829 0.009127668105065823 97388
26  1786870955715 0.009036785922944546 100995
27  1786885816421 0.008968348614871502 104602
28  1786900672938 0.008869677782058716 108209
29  1786915525104 0.008787780068814754 111816
30  1786930380011 0.008718393743038177 115423
31  1786945236798 0.008628121577203274 119030
32  1786960097003 0.008550820872187614 122637
33  1786974953580 0.008483502082526684 126244
34  1786989811549 0.008413978852331638 129851
35  1787004673512 0.008363179862499237 133458
36  1787019528669 0.008283094502985477 137065
37  1787034381140 0.008255121298134327 140672
38  1787049244716 0.008167064748704433 144279